import type { INodeProperties } from 'n8n-workflow';

import { documentIdField, getManyFields, omitFields, operationsFor } from './CommonDescription';

/** `Insights Dashboard v3` fields offered on create as well as update. */
const dashboardFields: INodeProperties[] = [
	{
		displayName: 'Is Public',
		name: 'is_public',
		type: 'boolean',
		default: false,
		description: 'Whether the dashboard can be viewed without logging in',
	},
	{
		displayName: 'Items (JSON)',
		name: 'items',
		type: 'json',
		default: '',
		placeholder: '[{"type":"chart","chart":"abc123de45","layout":{"x":0,"y":0,"w":12,"h":8}}]',
		description:
			'Content and layout of the dashboard: charts, filters and text areas, with their position in the grid',
	},
	{
		displayName: 'Preview Image',
		name: 'preview_image',
		type: 'string',
		default: '',
		description: 'URL of the thumbnail shown in the dashboard list',
	},
	{
		displayName: 'Share Link',
		name: 'share_link',
		type: 'string',
		default: '',
		description: 'Token of the public share link, generated by Insights',
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		default: '',
		description: 'Name of the dashboard, as shown in the workbook',
	},
	{
		displayName: 'Vertical Compact Layout',
		name: 'vertical_compact_layout',
		type: 'boolean',
		default: false,
		description: 'Whether items collapse upwards to fill vertical gaps',
	},
];

const REQUIRED_ON_CREATE = ['workbook'];

/**
 * `Insights Dashboard v3` stores its whole layout in the `items` JSON field rather than in
 * a child table. `linked_charts` is derived from it by Insights and marked read-only, so
 * the node does not expose it: writing `items` is what adds a chart to a dashboard.
 */
export const dashboardDescription: INodeProperties[] = [
	operationsFor('dashboard', 'dashboard'),
	{
		displayName: 'Workbook',
		name: 'workbook',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['dashboard'], operation: ['create'] } },
		description: 'The "name" field of the workbook holding the dashboard, e.g. 12',
	},
	documentIdField(
		'dashboard',
		'The Frappe record\'s "name" field, e.g. abc123de45. Visible in the URL of the Insights workbook.',
	),
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add field',
		default: {},
		displayOptions: { show: { resource: ['dashboard'], operation: ['create'] } },
		options: omitFields(dashboardFields, REQUIRED_ON_CREATE),
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add field',
		default: {},
		displayOptions: { show: { resource: ['dashboard'], operation: ['update'] } },
		options: dashboardFields,
	},
	...getManyFields('dashboard'),
];
